# SIEM Configuration

# Core Settings
core:
  log_level: INFO
  max_workers: 10
  event_batch_size: 100
  max_queue_size: 10000

# Storage Configuration
elasticsearch:
  host: "localhost:9200"
  user: "elastic"
  password: "changeme"
  indices:
    events: "siem-events"
    alerts: "siem-alerts"
    metrics: "siem-metrics"

# Metrics and Monitoring
prometheus:
  enabled: true
  port: 9090
  metrics_interval: 60

# Visualization
grafana:
  enabled: true
  host: "http://localhost:3000"
  user: "admin"
  password: "admin"
  dashboard_templates: "./config/dashboards"

# Security Components
security:
  # Intrusion Detection Systems
  suricata:
    enabled: true
    config_path: "./config/suricata/suricata.yaml"
    rules_path: "./config/suricata/rules"
    
  ossec:
    enabled: true
    config_path: "./config/ossec/ossec.conf"
    
  zeek:
    enabled: true
    scripts_path: "./config/zeek/scripts"
    
  yara:
    enabled: true
    rules_path: "./config/yara/rules"

# Network Monitoring
network:
  netflow:
    enabled: true
    host: "0.0.0.0"
    port: 2055
    
  packet_capture:
    enabled: true
    interface: "any"
    bpf_filter: "not port 22"

# Threat Intelligence
threat_intel:
  feeds:
    - name: "AlienVault OTX"
      url: "https://otx.alienvault.com/api/v1/pulses/subscribed"
      api_key: "your_key_here"
    - name: "VirusTotal"
      api_key: "your_key_here"
    - name: "AbuseIPDB"
      api_key: "your_key_here"

# Machine Learning
ml:
  models_path: "./config/ml_models"
  training_interval: 86400  # 24 hours
  anomaly_detection:
    contamination: 0.1
    features:
      - "cpu_usage"
      - "memory_usage"
      - "network_throughput"
      - "event_frequency"

# Response Actions
response:
  auto_response: true
  threshold: 8  # Severity threshold for automatic response
  actions:
    block_ip:
      enabled: true
      method: "iptables"
    kill_process:
      enabled: true
    isolate_system:
      enabled: true
      
# Alert Settings
alerts:
  severity_levels:
    critical: 9
    high: 7
    medium: 5
    low: 3
  notification:
    email:
      enabled: true
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: "your_email@gmail.com"
      password: "your_app_password"
      recipients:
        - "admin@company.com"
    slack:
      enabled: true
      webhook_url: "your_webhook_url"
    teams:
      enabled: false
      webhook_url: "your_webhook_url"

# System Monitoring
monitoring:
  system_metrics:
    enabled: true
    interval: 60
    thresholds:
      cpu_usage: 90
      memory_usage: 90
      disk_usage: 90
      
  process_monitoring:
    enabled: true
    interval: 30
    suspicious_patterns:
      - "cryptominer"
      - "malware"
      
  file_monitoring:
    enabled: true
    paths:
      - "/etc"
      - "/bin"
      - "/sbin"
    exclude:
      - "*.log"
      - "*.tmp"

# Logging
logging:
  file:
    enabled: true
    path: "./logs/siem.log"
    max_size: "100M"
    backup_count: 10
  syslog:
    enabled: true
    facility: "local0"
    
# API Configuration
api:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  ssl:
    enabled: true
    cert_file: "./config/ssl/cert.pem"
    key_file: "./config/ssl/key.pem"
  authentication:
    method: "jwt"
    secret_key: "your_secret_key"
    token_expiry: 3600

# Cloud Integration
cloud:
  aws:
    enabled: false
    region: "us-west-2"
    access_key: "your_access_key"
    secret_key: "your_secret_key"
    services:
      - "guardduty"
      - "securityhub"
      
  azure:
    enabled: false
    tenant_id: "your_tenant_id"
    client_id: "your_client_id"
    client_secret: "your_client_secret"
    subscription_id: "your_subscription_id"
    
  gcp:
    enabled: false
    project_id: "your_project_id"
    credentials_file: "./config/gcp/credentials.json"
