# SIEM Configuration

# Core Settings
core:
  log_level: INFO
  max_workers: 4
  event_batch_size: 100
  max_queue_size: 5000

# System Settings
system:
  name: "Enterprise SIEM"
  environment: "production"  # production, development, testing
  log_level: "INFO"
  secret_key: "${SIEM_SECRET_KEY}"  # Set this in environment variables

# Database Configuration
database:
  url: "sqlite+aiosqlite:///siem.db"
  pool_size: 20
  max_overflow: 10
  echo: false

# Web Interface
web:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 8080
  debug: false
  session_timeout: 3600  # 1 hour in seconds
  secret_key: "${SIEM_SECRET_KEY}"  # Set via environment variable
  session_type: "filesystem"

# Security Components
security:
  password_min_length: 12
  max_login_attempts: 5
  lockout_duration: 300  # 5 minutes in seconds
  session_token_expiry: 86400  # 24 hours in seconds
  allowed_hosts: ["localhost", "127.0.0.1"]

  # Windows Event Collection
  windows_events:
    enabled: true
    channels:
      - "Security"
      - "System"
      - "Application"
    max_events_per_batch: 1000
    poll_interval_seconds: 30

  # File System Monitoring
  file_monitoring:
    enabled: true
    paths:
      - "C:\\Windows\\System32\\config"
      - "C:\\Program Files"
      - "C:\\Program Files (x86)"
    ignore_patterns:
      - "*.tmp"
      - "*.log"
    poll_interval_seconds: 60

  # Network Monitoring
  network_monitoring:
    enabled: true
    interfaces:
      - "eth0"
      - "wlan0"
    capture_timeout_seconds: 300
    max_packet_size: 65535

# Monitoring
monitoring:
  windows_events:
    enabled: true
    logs: ["Security", "System", "Application"]
    interval: 10  # seconds
  
  network:
    enabled: true
    interface: "eth0"  # Change based on your network interface
    capture_timeout: 1000  # milliseconds
    max_packet_size: 65535
    protocols: ["TCP", "UDP", "ICMP"]

  system:
    enabled: true
    interval: 30  # seconds
    metrics:
      - cpu_usage
      - memory_usage
      - disk_usage
      - network_io
      - process_count

# Machine Learning
ml:
  enabled: true
  models:
    anomaly_detection:
      type: "isolation_forest"
      contamination: 0.1
      training_interval_hours: 24
    threat_classification:
      type: "random_forest"
      training_interval_hours: 48

# Machine Learning (New)
machine_learning:
  enabled: true
  models:
    anomaly_detection:
      enabled: true
      training_interval: 86400  # 24 hours
      threshold: 0.95
    threat_prediction:
      enabled: true
      update_interval: 3600  # 1 hour

# Alerts
alerts:
  severity_levels:
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW
    - INFO
  retention_days: 30
  max_alerts_per_minute: 1000
  notification:
    email:
      enabled: false
      smtp_server: "smtp.example.com"
      smtp_port: 587
      from_address: "siem@example.com"
    webhook:
      enabled: false
      url: "https://example.com/webhook"

# Offensive
offensive:
  enabled: true
  scan_interval: 3600  # 1 hour
  max_concurrent_scans: 5
  targets: []  # Add target IPs/networks here
  excluded_targets: []
  ports: [20, 21, 22, 23, 25, 53, 80, 443, 445, 3389]

# Defensive
defensive:
  enabled: true
  auto_block: true
  block_duration: 3600  # 1 hour
  whitelist: ["127.0.0.1"]
  blacklist: []
  rules:
    brute_force:
      max_attempts: 5
      window: 300  # 5 minutes
    suspicious_traffic:
      threshold: 1000  # connections per minute
    malware_detection:
      enabled: true
      scan_downloads: true

# Retention
retention:
  events_days: 30
  alerts_days: 90
  logs_days: 30
